// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuHR_lBB0l0ktwsJCMAXv-NnuHijSCak4',
    appId: '1:470809602430:web:a10b1187b8402b9f97ab2f',
    messagingSenderId: '470809602430',
    projectId: 'taskmanager-a3d7b1',
    authDomain: 'taskmanager-a3d7b1.firebaseapp.com',
    storageBucket: 'taskmanager-a3d7b1.appspot.com',
    measurementId: 'G-L4Y0HQP3BS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1ay1iDEQZGkKqvSdFuFNURbwT_YkMnLE',
    appId: '1:470809602430:android:cf6280c1621dc0dd97ab2f',
    messagingSenderId: '470809602430',
    projectId: 'taskmanager-a3d7b1',
    storageBucket: 'taskmanager-a3d7b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRz8beKmKGHydONTffSCxInheg-MpVJBI',
    appId: '1:470809602430:ios:f00592ecfe79e7eb97ab2f',
    messagingSenderId: '470809602430',
    projectId: 'taskmanager-a3d7b1',
    storageBucket: 'taskmanager-a3d7b1.appspot.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRz8beKmKGHydONTffSCxInheg-MpVJBI',
    appId: '1:470809602430:ios:f00592ecfe79e7eb97ab2f',
    messagingSenderId: '470809602430',
    projectId: 'taskmanager-a3d7b1',
    storageBucket: 'taskmanager-a3d7b1.appspot.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuHR_lBB0l0ktwsJCMAXv-NnuHijSCak4',
    appId: '1:470809602430:web:e66544e069904ee597ab2f',
    messagingSenderId: '470809602430',
    projectId: 'taskmanager-a3d7b1',
    authDomain: 'taskmanager-a3d7b1.firebaseapp.com',
    storageBucket: 'taskmanager-a3d7b1.appspot.com',
    measurementId: 'G-NEY9NGCJYY',
  );

}