// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHTZRFqNsS_w7rmH4n2hvWkzLGB47mvO8',
    appId: '1:1037777161868:web:62f1915163650ffbd875a9',
    messagingSenderId: '1037777161868',
    projectId: 'taskmanager-a3d7b',
    authDomain: 'taskmanager-a3d7b.firebaseapp.com',
    storageBucket: 'taskmanager-a3d7b.appspot.com',
    measurementId: 'G-Y28EPYWEPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBaNczWQJDIt5NIVRCftvHa-knVTsBZGQ',
    appId: '1:1037777161868:android:74a0a7e99ba24351d875a9',
    messagingSenderId: '1037777161868',
    projectId: 'taskmanager-a3d7b',
    storageBucket: 'taskmanager-a3d7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-IDH4A-3TUIJH0mH5YHYLP39TVUQCV98',
    appId: '1:1037777161868:ios:81bb75a883a435b9d875a9',
    messagingSenderId: '1037777161868',
    projectId: 'taskmanager-a3d7b',
    storageBucket: 'taskmanager-a3d7b.appspot.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-IDH4A-3TUIJH0mH5YHYLP39TVUQCV98',
    appId: '1:1037777161868:ios:81bb75a883a435b9d875a9',
    messagingSenderId: '1037777161868',
    projectId: 'taskmanager-a3d7b',
    storageBucket: 'taskmanager-a3d7b.appspot.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHTZRFqNsS_w7rmH4n2hvWkzLGB47mvO8',
    appId: '1:1037777161868:web:81cfeef90953afa0d875a9',
    messagingSenderId: '1037777161868',
    projectId: 'taskmanager-a3d7b',
    authDomain: 'taskmanager-a3d7b.firebaseapp.com',
    storageBucket: 'taskmanager-a3d7b.appspot.com',
    measurementId: 'G-3BDEYVG1MF',
  );

}